create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  page_key text not null,
  page_type text not null,
  current_index integer not null default 0,
  current_value text,
  completed boolean not null default false,
  total_items integer not null default 0,
  meta jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (user_id, page_key)
);

alter table public.profiles enable row level security;
alter table public.progress enable row level security;

drop policy if exists "Profiles are readable by owner" on public.profiles;
drop policy if exists "Profiles are insertable by owner" on public.profiles;
drop policy if exists "Profiles are updatable by owner" on public.profiles;
drop policy if exists "Progress is readable by owner" on public.progress;
drop policy if exists "Progress is insertable by owner" on public.progress;
drop policy if exists "Progress is updatable by owner" on public.progress;

create policy "Profiles are readable by owner" on public.profiles
  for select using (auth.uid() = id);

create policy "Profiles are insertable by owner" on public.profiles
  for insert with check (auth.uid() = id);

create policy "Profiles are updatable by owner" on public.profiles
  for update using (auth.uid() = id);

create policy "Progress is readable by owner" on public.progress
  for select using (auth.uid() = user_id);

create policy "Progress is insertable by owner" on public.progress
  for insert with check (auth.uid() = user_id);

create policy "Progress is updatable by owner" on public.progress
  for update using (auth.uid() = user_id);
